### ISSUE TITLE
Only works in api folder

### ISSUE THREAD

**Issue by luish000** [sane/sails-hook-babel#7]
Hi people:)

This hook only works in the api folder, in folders like config  not works

**Comment by krivaten** [comment]
+1

**Comment by shaunc** [comment]
+1 ... in fact, though I found that using `mocha --require babel-core/register` will test w/ es6 in config, but not run. Very annoying: I've build an app using TDD. It passes all of its tests, and now won't actually run. :(

Any suggestions for a workaround?

**Comment by shaunc** [comment]
ok ... workaround:

in `app.js` at the top put:

require("babel/register")({/* babel options */});

and then run using `node app.js`.

This completely skips the hook. A better workaround would be to load the hook in app.js, or at least get the babel options from the hook for DRY reasons. Still another possibility would be to add to the "core" -- after all sails "natively" supports coffeescript, etc.

**Comment by jackwanders** [comment]
+1, I just came across this issue. I am running `sails@0.11.3` with `sails-hook-babel@5.0.1`.

I was able to produce this issue when attempting to require an es6 module into `config/http.js` as a middleware:

```javascript
module.exports.http = {
  order: [
    ...
    'es6Logger'
    ...
  ],
  es6Logger: require('../utils/middleware/es6Logger')
};
```

Running `sails lift --verbose` produces the output:

```bash
verbose: Setting Node environment...
verbose: Please run `npm install coffee-script` to use coffescript (skipping for now)
verbose: moduleloader hook loaded successfully.
verbose: Loading app config...
/src/sails-project/utils/middleware/es6Logger.js:1
(function (exports, require, module, __filename, __dirname) { import winston from 'winston';
```

Given that `sails-hook-babel` produces verbose log output when it's successfully hooked (https://github.com/artificialio/sails-hook-babel/blob/master/index.js#L66), and that this output doesn't appear in the log above, it would appear that sails is loading the config before the babel hook. Indeed, when I remove the ES6 middleware, `sails lift --verbose` produces:

```bash
verbose: Setting Node environment...
verbose: Please run `npm install coffee-script` to use coffescript (skipping for now)
verbose: moduleloader hook loaded successfully.
verbose: Loading app config...
verbose: userconfig hook loaded successfully.
verbose: Exposing global variables... (you can disable this by modifying the properties in `sails.config.globals`)
verbose: Loading user hooks...
verbose: userhooks hook loaded successfully.
verbose: Babel hook activated. Enjoy ES6/7 power in your Sails app.
verbose: Loading runtime custom response definitions...
verbose: Loading app services...
verbose: logger hook loaded successfully.
verbose: request hook loaded successfully.
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Loading blueprint middleware...
verbose: blueprints hook loaded successfully.
verbose: responses hook loaded successfully.
verbose: controllers hook loaded successfully.
verbose: Loading policy modules from app...
verbose: Finished loading policy middleware logic.
verbose: policies hook loaded successfully.
verbose: services hook loaded successfully.
...
```

This confirms that `sails-hook-babel` will only successfully transpile source modules that are loaded after sails loads its user hooks, including, as the issue title indicates, everything within the `/api` directory: controllers, services, policies, etc.

In the near term, it seems @shaunc has the right approach; if you want to transpile ALL of your sails source code with babel, you need to register babel yourself before the app executes.

If you want to try running **ALL** of your sails app through babel, I would recommend the following steps:

First, uninstall `sails-hook-babel` if you have it installed and install some `babel` packages:

```bash
npm uninstall sails-hook-babel
npm install --save babel-core babel-preset-es2015
```

This will provide you with babel 6 and the necessary bundle of plugins that handle ES2015 > ES5 transpilation.

Next, update your `package.json` with a `babel` block so that your modules are transpiled using the ES2015 plugins:

```json
"babel": {
  "presets": [
    "es2015"
  ]
}
```

Now, you should be able to run `node -r babel-core/register app.js`.

> **NOTE**: When I did this on my app, I found some quirks in how sails processes modules when loading controllers and other modules. For example, `export default function somePolicyFn(req, res, next) {...}` resulted in an error when binding routes to the policy, but `module.exports = function somePolicyFn(req, res, next) {...}` did work. I haven't begun to debug why this happens, but at first glance, **sails does not appear ready to fully support ES2015 modules via babel**. Take this opinion for what it's worth. Just be aware that you may need to tweak some of your code to get it working the way you expect.

**Comment by eyasliu** [comment]
@jackwanders In this way, command `sails lift` and `sails console` didn't work.

**Comment by dangreen** [comment]
@luish000 @eyasliu you can use `babel-node`, just do something like `alias node="babel-node"`

**Comment by tylercollier** [comment]
Thanks for the notes @jackwanders. I was trying to use ES2015 syntax in `routes.js`, and saw what you saw: that the Sails bootstrapping process runs things like routes before loading its hooks, which won't work for ES2015 files.

@dangreen, is there any reason this issue is simply closed as dismissed? Without fixing this issue, I don't think the README can say "Just lift your app as normal, and enjoy the future of Javascript today". Perhaps you could add a caveat explaining in which circumstances it will work vs not?

**Comment by dangreen** [comment]
@tylercollier "that the Sails bootstrapping process runs things like routes before loading its hooks" there is no method to apply babel for `config` dir. I already sad "you can use babel-node, just do something like `alias node="babel-node"`"

**Comment by tylercollier** [comment]
Thanks for the suggestion. If I used babel-node in the way you suggested, would there be any reason to use sails-hook-babel? babel-node basically covers every case, right?
